### ISSUE TITLE
Unable to nest SerializableInterfaces

### ISSUE THREAD

**Issue by sandsalamand** [Thundernerd/Unity3D-SerializableInterface#59]
**Describe the bug**
Unable to nest SerializableInterfaces of non-Unity objects.

**To Reproduce**
Create a field of SerializableInterface<T>, then, in the Inspector, assign to it a non-Unity class which contains its own field of SerializableInterface<T>.

`[SerializeField] private SerializableInterface<IInteraction> parentInteraction;`

```
public class BoilerValve : IInteraction
{
	[SerializeField] SerializableInterface<IInteraction> nestedIInteraction;
}
```

**Expected behavior**
The nested field would be assignable in the inspector to a class that implements IInteraction.

**Screenshots**
![image](https://github.com/Thundernerd/Unity3D-SerializableInterface/assets/38278077/02799ccf-663c-4bcd-a14c-396311ee8720)

**Desktop (please complete the following information):**
Windows 10

**Unity (please complete the following information):**
2022.2.11f1

**Additional context**
N/A

**Comment by Thundernerd** [comment]
Unfortunately I am unable to reproduce this.
![image](https://github.com/Thundernerd/Unity3D-SerializableInterface/assets/5531467/d1833cdf-404c-4aff-a223-a4800ed8bb24)

My setup is as follows:

I have an `IInteraction` interface
```csharp
public interface IInteraction
{
}
```

An implementation class like so
```csharp
using TNRD;
using UnityEngine;

public class Interaction : IInteraction
{
    [SerializeField] private SerializableInterface<IInteraction> nestedInteraction;
}
```

And a test behaviour like this
```csharp
using TNRD;
using UnityEngine;

public class TesterBehaviour : MonoBehaviour
{
    [SerializeField] private SerializableInterface<IInteraction> rootInteraction;
}
```

I simply added the `TesterBehaviour` to a component and started selecting the regular `Interaction` class which resulted in the expected behaviour.

If you are able to reproduce it could you potentially submit a test project somewhere?

**Comment by sandsalamand** [comment]
I wasn't able to reproduce it in a fresh project, so it seems like the issue is in my code. I looked through all of my Editor scripts and plugins, and I imported the important ones into the fresh project, but I still wasn't able to reproduce it there. I guess I'll just have to accept this bug :/
